CREATE TABLE IF NOT EXISTS personal (
  id SERIAL PRIMARY KEY,
  nombre VARCHAR(120) NOT NULL,
  apellido VARCHAR(120) NOT NULL,
  cargo VARCHAR(120) NOT NULL,
  email VARCHAR(160) NOT NULL UNIQUE,
  telefono VARCHAR(40),
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

GRANT CONNECT ON DATABASE crud_personal TO crud_user;
GRANT USAGE ON SCHEMA public TO crud_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE personal TO crud_user;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO crud_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO crud_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT USAGE, SELECT ON SEQUENCES TO crud_user;
